### PR TITLE
Update some dependencies and support PHP8

### PR DESCRIPTION
**Pull request by Tjoosten**
Updated some package dependencies for Support Laravel 8. Also i bumped the supported php version and added php 8. 

Because following the following page. (https://www.php.net/supported-versions.php)
php 7.2 is not actively maintained anymore

### CODE REVIEW

**Comment by czim** [comment]
Thanks for your work. I agree with the version bump, but not with increasing the minimum required version. Though it is not recommended to use older Laravel & PHP versions, this package still works with them. I'll make the changes, but keep the lower limit as it currently is.

If you can make the php requirement `^7.2|^8.0` and the illuminate requirements `^6|^7|^8`, that'd be great.

**Comment by Tjoosten** [comment]
Hey Czim, 

Thanks for your response. I will make the changes somewhere next week. Ill keep you posted

**Comment by Tjoosten** [comment]
hey @czim 

I lowered the version bump. Can u review and tell me if something more is needed.

**Comment by czim** [comment]
Looks great, thanks a lot!

**Pull request merged**
